import Link from 'next/link';
import {ArrowRight,ChartNoAxesCombined,ShieldCheck,ScanQrCode,ShoppingBag,MessageCircle,ReceiptText} from 'lucide-react';
export default function Home(){
return <main className="landing">
 <header className="landing-nav"><Link href="/" className="brand-brand"><span className="brand-symbol"><ShoppingBag size={22}/></span><span>titiplen<span className="brand-dot">.id</span></span></Link><nav><Link href="/admin" className="nav-minor">Admin</Link><Link href="/cek-invoice" className="button button-dark button-small">Cek invoice <ArrowRight size={16}/></Link></nav></header>
 <div className="hero"><div className="hero-copy"><span className="eyebrow"><span className="live-dot"/> JASTIP, TAPI LEBIH SIMPLE</span><h1>Titipan aman.<br/><em>Bayarnya nyaman.</em></h1><p>Cek semua barang titipan, lihat rincian tagihan, dan bayar lewat QRIS dalam satu tempat. Nggak perlu scroll chat panjang lagi.</p><div className="hero-cta"><Link href="/cek-invoice" className="button button-dark">Cek pesanan saya <ArrowRight size={18}/></Link><span>Siapkan nomor WhatsApp kamu ✨</span></div><div className="hero-highlights"><span><ShieldCheck size={17}/> Data pesanan privat</span><span><ScanQrCode size={17}/> Bayar dengan QRIS</span></div></div>
 <div className="hero-visual"><div className="orb orb-one"/><div className="orb orb-two"/><div className="mock-receipt"><div className="mock-title"><span className="brand-symbol mini"><ShoppingBag size={19}/></span><span>Ringkasan titipan<small>Invoice #TPL-2026-00001</small></span><span className="pill paid">● Sudah lunas</span></div><div className="receipt-product"><span className="product-avatar lilac">✦</span><div><strong>Beauty essentials</strong><small>Beauty Expo Jakarta · 2 barang</small></div><strong>Rp296.000</strong></div><div className="receipt-product"><span className="product-avatar blush">♡</span><div><strong>Kidswear collection</strong><small>Kidswear Pop-up · 1 barang</small></div><strong>Rp135.000</strong></div><div className="receipt-divider"/><div className="receipt-total"><span>Total belanja</span><strong>Rp431.000</strong></div><div className="receipt-footer"><span>Thank you for shopping with us!</span><span>♥</span></div></div><div className="floating-note"><span className="note-icon"><MessageCircle size={19}/></span><span><strong>Gampang konfirmasi</strong><small>Langsung ke WhatsApp admin</small></span></div></div></div>
 <section className="landing-features"><div className="section-heading"><span className="eyebrow">SATU TEMPAT UNTUK SEMUANYA</span><h2>Nggak ribet, nggak bingung.</h2></div><div className="feature-grid"><article><div className="feature-icon"><ReceiptText/></div><h3>Rincian lengkap</h3><p>Lihat barang, ukuran, jumlah, biaya jastip, hingga total tagihan dengan jelas.</p></article><article><div className="feature-icon"><ScanQrCode/></div><h3>QRIS siap bayar</h3><p>QRIS Titiplen tampil bersama invoice. Bayar dan konfirmasi langsung ke admin.</p></article><article><div className="feature-icon"><ChartNoAxesCombined/></div><h3>Status selalu jelas</h3><p>Ketahui invoice yang belum dibayar, sedang DP, atau sudah lunas.</p></article></div></section>
 <footer className="landing-footer"><strong>titiplen.id</strong><span>Everything you love, we help you get. ♡</span><Link href="/admin">Admin area <ArrowRight size={14}/></Link></footer>
 </main>
}
